process.env.PORT = 8000
process.env.WORDPRESS_URL = 'https://wordpressurl.com'
process.env.WOOCOMMERCE_CONSUMER_KEY = 'WOOCOMMERCE_CONSUMER_KEY'
process.env.WOOCOMMERCE_CONSUMER_SECRET = 'WOOCOMMERCE_CONSUMER_SECRET'
